menu:
  主页: /
  作品: /works
  联系我: /contact

widgets:

excerpt_link: 查看全文

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: false

google_analytics:
baidu_analytics: f67f679842d89dcdbd978d4f954af51e
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
